import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0d1117',
  },
  screen: {
    padding: 16,
  },
  title: {
    color: '#f0f6fc',
    fontSize: 24,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 12,
  },
  label: {
    color: '#f0f6fc',
    marginBottom: 6,
  },
  muted: {
    color: '#8b949e',
    marginBottom: 8,
  },
  error: {
    color: '#ff7b72',
    marginTop: 8,
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  input: {
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 8,
    color: '#f0f6fc',
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 10,
  },
  button: {
    backgroundColor: '#238636',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  buttonSecondary: {
    backgroundColor: '#1f6feb',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  buttonDanger: {
    backgroundColor: '#da3633',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  buttonDangerInline: {
    backgroundColor: '#da3633',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  buttonContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    marginBottom: 8,
  },
  iconButtonPrimary: {
    backgroundColor: '#238636',
    borderWidth: 1,
    borderColor: '#2ea043',
  },
  iconButtonSecondary: {
    backgroundColor: '#1f6feb',
    borderWidth: 1,
    borderColor: '#388bfd',
  },
  iconButtonDanger: {
    backgroundColor: '#da3633',
    borderWidth: 1,
    borderColor: '#f85149',
  },
  iconButtonGhost: {
    backgroundColor: '#21262d',
    borderWidth: 1,
    borderColor: '#30363d',
  },
  inlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  inlineLeft: {
    flex: 1,
    marginRight: 8,
  },
  inlineAction: {
    marginRight: 0,
    marginBottom: 0,
    alignSelf: 'center',
  },
  messageComposerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  messageInput: {
    flex: 1,
    marginBottom: 0,
    marginRight: 8,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  fab: {
    position: 'absolute',
    right: 18,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#238636',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2ea043',
  },
  fabText: {
    color: '#ffffff',
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 34,
    marginTop: -2,
  },
  entryComposer: {
    backgroundColor: '#161b22',
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 12,
    padding: 12,
  },
  entryComposerWrap: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 24,
  },
  entryModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    justifyContent: 'flex-end',
    paddingBottom: 16,
  },
  entryKeyboardAvoiding: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  entryModalCard: {
    marginTop: 0,
    marginBottom: 0,
    maxHeight: '78%',
  },
  entryComposerScrollContent: {
    paddingBottom: 8,
  },
  card: {
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  cardTitle: {
    color: '#f0f6fc',
    fontWeight: '700',
    marginBottom: 4,
  },
  cardBody: {
    color: '#c9d1d9',
    marginBottom: 4,
  },
  chatGroupMessage: {
    color: '#c9d1d9',
    marginBottom: 4,
  },
  chatGroupMessageLast: {
    marginBottom: 2,
  },
  linkDanger: {
    color: '#ff7b72',
    marginTop: 6,
  },
  tabRow: {
    flexDirection: 'row',
    borderBottomColor: '#30363d',
    borderBottomWidth: 1,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
  },
  tabButtonActive: {
    backgroundColor: '#161b22',
  },
  tabButtonText: {
    color: '#f0f6fc',
    fontWeight: '600',
    fontSize: 12,
  },
  sectionTitle: {
    color: '#f0f6fc',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 10,
    marginBottom: 8,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileHeaderText: {
    flex: 1,
    marginLeft: 12,
  },
  avatarSquare: {
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  chatInboxActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  chatFloatingHost: {
    position: 'relative',
    zIndex: 120,
  },
  chatScreenWrap: {
    position: 'relative',
  },
  dropdownBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 110,
  },
  floatingDropdown: {
    position: 'absolute',
    left: 0,
    right: 0,
    maxHeight: 360,
    backgroundColor: '#161b22',
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    zIndex: 130,
  },
  floatingDropdownInbox: {
    top: 116,
  },
  floatingDropdownRoom: {
    top: 160,
  },
  dropdownItem: {
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 8,
    padding: 8,
    marginBottom: 8,
  },
  chatListItem: {
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    backgroundColor: '#161b22',
  },
  chatListItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chatBadge: {
    color: '#0d1117',
    backgroundColor: '#f2cc60',
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 2,
    fontSize: 12,
    fontWeight: '700',
  },
  chatRoomHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  socialWrap: {
    position: 'relative',
  },
  socialHeader: {
    marginBottom: 8,
  },
  segmentRow: {
    flexDirection: 'row',
    backgroundColor: '#161b22',
    borderRadius: 10,
    padding: 4,
    borderWidth: 1,
    borderColor: '#30363d',
    marginBottom: 8,
  },
  segmentButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 8,
  },
  segmentButtonActive: {
    backgroundColor: '#1f6feb',
  },
  segmentText: {
    color: '#f0f6fc',
    fontWeight: '600',
  },
  socialActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  socialDropdown: {
    top: 56,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    justifyContent: 'flex-start',
  },
  modalCard: {
    marginHorizontal: 16,
    marginTop: 120,
    backgroundColor: '#161b22',
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    maxHeight: '70%',
  },
  socialModalCard: {
    marginTop: 180,
  },
  chatModalCard: {
    marginTop: 130,
  },
  entryActionsModalCard: {
    marginTop: 220,
  },
  homeSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  monthStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  monthStatCard: {
    width: '48%',
    borderWidth: 1,
    borderColor: '#30363d',
    backgroundColor: '#161b22',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  monthStatValue: {
    color: '#f0f6fc',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 2,
  },
  monthStatLabel: {
    color: '#8b949e',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  monthTipCard: {
    borderWidth: 1,
    borderColor: '#30363d',
    backgroundColor: '#161b22',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  monthTipTitle: {
    color: '#f0f6fc',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 4,
  },
  monthTipText: {
    color: '#c9d1d9',
    fontSize: 13,
    lineHeight: 18,
  },
  calendarCard: {
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 10,
    backgroundColor: '#121821',
    padding: 10,
    marginBottom: 12,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  calendarTitle: {
    color: '#f0f6fc',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  calendarMonthButton: {
    width: 32,
    height: 32,
    marginRight: 0,
    marginBottom: 0,
  },
  calendarWeekRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  calendarWeekday: {
    width: '14.28%',
    textAlign: 'center',
    color: '#8b949e',
    fontSize: 11,
    fontWeight: '600',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  calendarCell: {
    width: '14.2857%',
    height: 36,
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#161b22',
    marginBottom: 4,
    position: 'relative',
    overflow: 'hidden',
  },
  calendarCellOutside: {
    borderColor: '#1f2937',
    backgroundColor: '#0f141b',
    opacity: 0.7,
  },
  calendarCellToday: {
    borderWidth: 2,
    borderColor: '#58a6ff',
    shadowColor: '#58a6ff',
    shadowOpacity: 0.35,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  calendarCellText: {
    color: '#f0f6fc',
    fontSize: 12,
    fontWeight: '600',
  },
  calendarEntryMarkerRow: {
    position: 'absolute',
    top: 3,
    right: 3,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  calendarEntryDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#c9d1d9',
  },
  calendarEntryDotOutside: {
    opacity: 0.75,
  },
  calendarEntryPlus: {
    color: '#c9d1d9',
    fontSize: 8,
    fontWeight: '700',
    lineHeight: 8,
  },
  calendarCellTextToday: {
    color: '#ffffff',
    fontWeight: '800',
  },
  calendarCellTextOutside: {
    color: '#6e7681',
  },
  calendarLegendRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
  },
  calendarLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  calendarLegendSwatch: {
    width: 12,
    height: 12,
    borderRadius: 4,
    borderWidth: 1,
  },
  calendarLegendText: {
    color: '#8b949e',
    fontSize: 10,
  },
  entryRail: {
    paddingBottom: 10,
    paddingRight: 8,
  },
  entrySquareCard: {
    width: 160,
    height: 160,
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    marginRight: 10,
    backgroundColor: '#161b22',
    alignItems: 'center',
  },
  entrySquareTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    position: 'relative',
    marginBottom: 6,
  },
  entrySquareMenuButton: {
    position: 'absolute',
    right: 0,
    top: 2,
  },
  entryTypeChip: {
    height: 24,
    minWidth: 64,
    borderRadius: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#30363d',
    backgroundColor: '#0f141b',
    justifyContent: 'center',
  },
  entryTypeDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 4,
  },
  entryTypeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#7b4d2a',
  },
  entryTypeDotHard: {
    backgroundColor: '#6d3f20',
  },
  entryTypeDotSoft: {
    backgroundColor: '#94623a',
  },
  entryTypePillLumpy: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#7f512d',
    position: 'relative',
  },
  entryTypeNotchA: {
    position: 'absolute',
    top: -1,
    left: 12,
    width: 6,
    height: 4,
    borderRadius: 3,
    backgroundColor: '#0f141b',
  },
  entryTypeNotchB: {
    position: 'absolute',
    bottom: -1,
    right: 16,
    width: 7,
    height: 4,
    borderRadius: 3,
    backgroundColor: '#0f141b',
  },
  entryTypePillCracked: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#8d5a32',
    position: 'relative',
    overflow: 'hidden',
  },
  entryTypeCrackA: {
    position: 'absolute',
    left: 14,
    top: 1,
    width: 1,
    height: 8,
    backgroundColor: '#5a341a',
    transform: [{ rotate: '14deg' }],
  },
  entryTypeCrackB: {
    position: 'absolute',
    right: 16,
    top: 1,
    width: 1,
    height: 8,
    backgroundColor: '#5a341a',
    transform: [{ rotate: '-12deg' }],
  },
  entryTypePillSmooth: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#9e6a3d',
    position: 'relative',
    overflow: 'hidden',
  },
  entryTypeHighlight: {
    position: 'absolute',
    left: 8,
    right: 8,
    top: 1,
    height: 2,
    borderRadius: 2,
    backgroundColor: '#c89262',
    opacity: 0.8,
  },
  entryTypeMushy: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#a87548',
    position: 'relative',
    overflow: 'hidden',
  },
  entryTypeMushyLayer: {
    position: 'absolute',
    left: 6,
    right: 6,
    top: 2,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#8f5f35',
    opacity: 0.8,
  },
  entryTypeMushyLayerSmall: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 1,
    height: 2,
    borderRadius: 2,
    backgroundColor: '#7d4f2b',
    opacity: 0.8,
  },
  entryTypeLiquid: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#b48356',
    position: 'relative',
    overflow: 'hidden',
  },
  entryTypeWaveA: {
    position: 'absolute',
    left: 6,
    right: 8,
    top: 3,
    height: 1,
    backgroundColor: '#8b5a33',
    opacity: 0.8,
  },
  entryTypeWaveB: {
    position: 'absolute',
    left: 10,
    right: 5,
    top: 6,
    height: 1,
    backgroundColor: '#7b4a25',
    opacity: 0.7,
  },
  entrySquareRating: {
    fontWeight: '700',
    marginBottom: 4,
    textAlign: 'center',
  },
  entrySquareTime: {
    color: '#8b949e',
    marginBottom: 6,
    textAlign: 'center',
  },
  entrySquareNote: {
    color: '#c9d1d9',
    flex: 1,
    textAlign: 'center',
    width: '100%',
  },
  entryInlineMenu: {
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: '#0f141b',
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 8,
    padding: 6,
    zIndex: 50,
  },
  entryInlineMenuAction: {
    alignSelf: 'stretch',
    marginRight: 0,
    marginBottom: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  entryMenuBackdrop: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  bristolGuide: {
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 10,
    padding: 8,
    marginBottom: 10,
    backgroundColor: '#0f141b',
  },
  bristolGuideRow: {
    color: '#c9d1d9',
    marginBottom: 3,
    fontSize: 12,
  },
  sliderEndLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
    marginBottom: 8,
  },
  sliderEndLabel: {
    color: '#8b949e',
    fontSize: 11,
  },
  dateTimePickerWrap: {
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 10,
    padding: 8,
    backgroundColor: '#121821',
  },
  dateTimeSpacer: {
    width: 8,
  },
  ratingVisualCard: {
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 10,
    padding: 8,
    marginBottom: 8,
    backgroundColor: '#121821',
  },
  ratingVisualTitle: {
    color: '#c9d1d9',
    fontSize: 12,
    marginBottom: 6,
  },
  ratingPillRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 4,
  },
  ratingPill: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 4,
    backgroundColor: '#0f141b',
    alignItems: 'center',
  },
  ratingPillActive: {
    borderWidth: 2,
    transform: [{ translateY: -1 }],
  },
  ratingPillEmoji: {
    color: '#f0f6fc',
    fontSize: 14,
    fontWeight: '700',
  },
  ratingPillLabel: {
    color: '#8b949e',
    fontSize: 10,
    marginTop: 2,
    textAlign: 'center',
  },
  bristolVisualCard: {
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    backgroundColor: '#121821',
    alignItems: 'center',
    overflow: 'hidden',
  },
  bristolVisualGlyphWrap: {
    height: 26,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bristolVisualText: {
    color: '#c9d1d9',
    fontSize: 12,
    marginTop: 8,
  },
  bristolDotsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  bristolDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    overflow: 'hidden',
  },
  bristolBlob: {
    width: 14,
    height: 11,
    borderRadius: 7,
  },
  bristolDotHard: {
    backgroundColor: '#8a6a4f',
  },
  bristolDotSoft: {
    backgroundColor: '#a88360',
  },
  bristolDotSkewA: {
    transform: [{ rotate: '-11deg' }],
  },
  bristolDotSkewB: {
    transform: [{ rotate: '8deg' }],
  },
  bristolBlobA: {
    transform: [{ rotate: '-14deg' }],
  },
  bristolBlobB: {
    transform: [{ rotate: '10deg' }],
  },
  bristolLumpySausage: {
    width: 110,
    height: 18,
    borderRadius: 10,
    backgroundColor: '#8a6a4f',
    borderWidth: 2,
    borderColor: '#6a4f3a',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  bristolContourLine: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: 'rgba(70,50,37,0.5)',
  },
  bristolTextureRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  bristolTextureDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#5b4532',
  },
  bristolSmoothSausage: {
    width: 120,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#9a7755',
    overflow: 'hidden',
  },
  bristolCracked: {
    borderTopWidth: 2,
    borderTopColor: '#6a4f3a',
  },
  bristolCrackMarkA: {
    position: 'absolute',
    top: 4,
    left: 28,
    width: 10,
    height: 2,
    backgroundColor: '#6a4f3a',
    transform: [{ rotate: '-23deg' }],
  },
  bristolCrackMarkB: {
    position: 'absolute',
    top: 5,
    left: 55,
    width: 9,
    height: 2,
    backgroundColor: '#6a4f3a',
    transform: [{ rotate: '18deg' }],
  },
  bristolCrackMarkC: {
    position: 'absolute',
    top: 5,
    left: 83,
    width: 9,
    height: 2,
    backgroundColor: '#6a4f3a',
    transform: [{ rotate: '-16deg' }],
  },
  bristolHighlight: {
    position: 'absolute',
    top: 2,
    left: 12,
    right: 24,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(240,246,252,0.25)',
  },
  bristolHighlightSoft: {
    position: 'absolute',
    top: 7,
    left: 24,
    right: 32,
    height: 2,
    borderRadius: 2,
    backgroundColor: 'rgba(240,246,252,0.16)',
  },
  bristolShadowBand: {
    position: 'absolute',
    left: 8,
    right: 8,
    bottom: 2,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(60,42,30,0.35)',
  },
  bristolMushy: {
    width: 120,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#b08a66',
    opacity: 0.85,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  bristolMushyLayer: {
    position: 'absolute',
    left: 10,
    right: 10,
    height: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(140,102,72,0.45)',
  },
  bristolMushyLayerSmall: {
    position: 'absolute',
    left: 35,
    right: 35,
    height: 7,
    borderRadius: 6,
    backgroundColor: 'rgba(90,63,44,0.35)',
  },
  bristolMushyGrainA: {
    position: 'absolute',
    left: 20,
    top: 6,
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(95,70,49,0.4)',
  },
  bristolMushyGrainB: {
    position: 'absolute',
    right: 24,
    bottom: 5,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(95,70,49,0.35)',
  },
  bristolLiquid: {
    width: 120,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#c8a27e',
    opacity: 0.7,
    overflow: 'hidden',
  },
  bristolWaveA: {
    position: 'absolute',
    left: -6,
    right: -6,
    top: 3,
    height: 4,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  bristolWaveB: {
    position: 'absolute',
    left: -12,
    right: -12,
    bottom: 2,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(110,84,64,0.35)',
  },
  bristolWaveC: {
    position: 'absolute',
    left: 8,
    right: 24,
    top: 1,
    height: 2,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  bristolDotSpecular: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(240,246,252,0.18)',
  },
  bristolDotSpecularSoft: {
    position: 'absolute',
    top: 2,
    left: 3,
    width: 4,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(240,246,252,0.15)',
  },
});
