import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0d1117',
  },
  screen: {
    padding: 16,
  },
  title: {
    color: '#f0f6fc',
    fontSize: 24,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 12,
  },
  label: {
    color: '#f0f6fc',
    marginBottom: 6,
  },
  muted: {
    color: '#8b949e',
    marginBottom: 8,
  },
  error: {
    color: '#ff7b72',
    marginTop: 8,
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  input: {
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 8,
    color: '#f0f6fc',
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 10,
  },
  button: {
    backgroundColor: '#238636',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  buttonSecondary: {
    backgroundColor: '#1f6feb',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  buttonDanger: {
    backgroundColor: '#da3633',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  buttonDangerInline: {
    backgroundColor: '#da3633',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  fab: {
    position: 'absolute',
    right: 18,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#238636',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2ea043',
  },
  fabText: {
    color: '#ffffff',
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 34,
    marginTop: -2,
  },
  entryComposer: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 96,
    backgroundColor: '#161b22',
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 12,
    padding: 12,
  },
  card: {
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  cardTitle: {
    color: '#f0f6fc',
    fontWeight: '700',
    marginBottom: 4,
  },
  cardBody: {
    color: '#c9d1d9',
    marginBottom: 4,
  },
  linkDanger: {
    color: '#ff7b72',
    marginTop: 6,
  },
  tabRow: {
    flexDirection: 'row',
    borderBottomColor: '#30363d',
    borderBottomWidth: 1,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
  },
  tabButtonActive: {
    backgroundColor: '#161b22',
  },
  tabButtonText: {
    color: '#f0f6fc',
    fontWeight: '600',
    fontSize: 12,
  },
  sectionTitle: {
    color: '#f0f6fc',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 10,
    marginBottom: 8,
  },
  chatInboxActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  chatFloatingHost: {
    position: 'relative',
    zIndex: 10,
  },
  chatScreenWrap: {
    position: 'relative',
  },
  dropdownBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 40,
  },
  floatingDropdown: {
    position: 'absolute',
    left: 0,
    right: 0,
    maxHeight: 360,
    backgroundColor: '#161b22',
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    zIndex: 50,
  },
  floatingDropdownInbox: {
    top: 116,
  },
  floatingDropdownRoom: {
    top: 160,
  },
  dropdownItem: {
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 8,
    padding: 8,
    marginBottom: 8,
  },
  chatListItem: {
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    backgroundColor: '#161b22',
  },
  chatListItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chatBadge: {
    color: '#0d1117',
    backgroundColor: '#f2cc60',
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 2,
    fontSize: 12,
    fontWeight: '700',
  },
  chatRoomHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  socialWrap: {
    position: 'relative',
  },
  socialHeader: {
    marginBottom: 8,
  },
  segmentRow: {
    flexDirection: 'row',
    backgroundColor: '#161b22',
    borderRadius: 10,
    padding: 4,
    borderWidth: 1,
    borderColor: '#30363d',
    marginBottom: 8,
  },
  segmentButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 8,
  },
  segmentButtonActive: {
    backgroundColor: '#1f6feb',
  },
  segmentText: {
    color: '#f0f6fc',
    fontWeight: '600',
  },
  socialActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  socialDropdown: {
    top: 56,
  },
});
