import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#0d1117',
  },
  rootLight: {
    backgroundColor: '#f3f5f8',
  },
  contentWithTabIsland: {
    flex: 1,
    paddingBottom: 0,
  },
  contentWithTabIslandLight: {
    backgroundColor: '#f3f5f8',
  },
  screen: {
    padding: 16,
  },
  refreshGapIndicator: {
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  refreshHint: {
    color: '#8b949e',
    fontSize: 12,
    fontWeight: '600',
  },
  title: {
    color: '#f0f6fc',
    fontSize: 24,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 12,
  },
  label: {
    color: '#f0f6fc',
    marginBottom: 6,
  },
  muted: {
    color: '#8b949e',
    marginBottom: 8,
  },
  error: {
    color: '#ff7b72',
    marginTop: 8,
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  input: {
    borderColor: '#1b2330',
    borderWidth: 0,
    borderRadius: 8,
    backgroundColor: '#10161f',
    color: '#f0f6fc',
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 10,
  },
  button: {
    backgroundColor: '#238636',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  buttonSecondary: {
    backgroundColor: '#1f6feb',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  buttonDanger: {
    backgroundColor: '#da3633',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  buttonDangerInline: {
    backgroundColor: '#da3633',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '600',
  },
  buttonContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    marginBottom: 8,
  },
  iconButtonPrimary: {
    backgroundColor: '#238636',
    borderWidth: 1,
    borderColor: '#2ea043',
  },
  iconButtonSecondary: {
    backgroundColor: '#1f6feb',
    borderWidth: 1,
    borderColor: '#388bfd',
  },
  iconButtonDanger: {
    backgroundColor: '#da3633',
    borderWidth: 1,
    borderColor: '#f85149',
  },
  iconButtonGhost: {
    backgroundColor: '#21262d',
    borderWidth: 1,
    borderColor: '#30363d',
  },
  inlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  inlineLeft: {
    flex: 1,
    marginRight: 8,
  },
  inlineAction: {
    marginRight: 0,
    marginBottom: 0,
    alignSelf: 'center',
  },
  messageComposerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  messageInput: {
    flex: 1,
    marginBottom: 0,
    marginRight: 8,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  appActionButtonPrimary: {
    minHeight: 44,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 10,
    backgroundColor: '#1f6feb',
    borderWidth: 1,
    borderColor: '#388bfd',
    alignSelf: 'stretch',
    justifyContent: 'center',
  },
  appActionButtonSecondary: {
    minHeight: 40,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 8,
    backgroundColor: '#161b22',
    borderWidth: 1,
    borderColor: '#2f3f54',
    alignSelf: 'flex-start',
    justifyContent: 'center',
  },
  appActionButtonDanger: {
    minHeight: 42,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginTop: 10,
    marginBottom: 8,
    backgroundColor: '#301417',
    borderWidth: 1,
    borderColor: '#8f3c42',
    alignSelf: 'flex-start',
    justifyContent: 'center',
  },
  fab: {
    position: 'absolute',
    right: 18,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#238636',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2ea043',
  },
  fabText: {
    color: '#ffffff',
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 34,
    marginTop: -2,
  },
  entryComposer: {
    backgroundColor: '#161b22',
    borderRadius: 12,
    padding: 12,
  },
  entryComposerWrap: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 24,
  },
  entryInlineOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 40,
  },
  entryComposerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
  },
  entryModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.06)',
    justifyContent: 'flex-end',
    paddingBottom: 10,
    paddingHorizontal: 10,
  },
  entryKeyboardAvoiding: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  entryModalCard: {
    marginTop: 0,
    marginBottom: 0,
    maxHeight: '62%',
  },
  entryComposerScrollContent: {
    paddingBottom: 8,
  },
  entryProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 8,
  },
  entryProgressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#30363d',
  },
  entryProgressDotActive: {
    width: 18,
    backgroundColor: '#58a6ff',
  },
  entryPager: {
    height: 270,
  },
  entryStepPane: {
    paddingTop: 4,
    paddingHorizontal: 2,
  },
  entryDateToggleRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  entryDateToggleButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 999,
    backgroundColor: '#0f141b',
    paddingVertical: 7,
    alignItems: 'center',
  },
  entryDateToggleButtonActive: {
    backgroundColor: '#1f6feb',
    borderColor: '#388bfd',
  },
  entryDateToggleText: {
    color: '#f0f6fc',
    fontSize: 12,
    fontWeight: '700',
  },
  entryNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 8,
  },
  entryNavButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 14,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  entryNavButtonIconOnly: {
    flex: 0,
    width: 56,
    minHeight: 56,
    borderRadius: 16,
    paddingHorizontal: 0,
    gap: 0,
  },
  entryNavButtonPrimary: {
    backgroundColor: '#1f6feb',
    borderWidth: 1,
    borderColor: '#388bfd',
  },
  entryNavButtonSecondary: {
    backgroundColor: '#161b22',
    borderWidth: 1,
    borderColor: '#30363d',
  },
  entryNavButtonText: {
    color: '#f0f6fc',
    fontWeight: '600',
  },
  entryNavButtonTextPrimary: {
    color: '#ffffff',
    fontWeight: '700',
  },
  card: {
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  cardTitle: {
    color: '#f0f6fc',
    fontWeight: '700',
    marginBottom: 4,
  },
  cardBody: {
    color: '#c9d1d9',
    marginBottom: 4,
  },
  feedCommentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 6,
    gap: 6,
  },
  feedMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: 6,
    gap: 8,
  },
  feedHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 6,
  },
  feedIdentityWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  feedStatsColumn: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 6,
  },
  feedIdentityMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
  },
  feedMetaInline: {
    color: '#c9d1d9',
    fontSize: 13,
    textAlign: 'right',
  },
  feedMetaTime: {
    color: '#8b949e',
    fontSize: 12,
  },
  feedActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 2,
    marginBottom: 4,
  },
  feedReactionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
    marginBottom: 8,
  },
  feedReactionChip: {
    minHeight: 28,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  feedReactionEmoji: {
    fontSize: 14,
  },
  feedReactionCount: {
    fontSize: 11,
    fontWeight: '700',
  },
  feedActionButton: {
    minHeight: 30,
    borderRadius: 15,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 0,
    marginRight: 0,
  },
  feedActionText: {
    color: '#c9d1d9',
    fontSize: 12,
    fontWeight: '600',
  },
  feedCommentBodyWrap: {
    flex: 1,
  },
  feedCommentAuthor: {
    color: '#f0f6fc',
    fontSize: 12,
    fontWeight: '600',
  },
  feedCommentText: {
    color: '#c9d1d9',
    fontSize: 12,
  },
  feedCommentTime: {
    color: '#8b949e',
    fontSize: 11,
    marginTop: 2,
  },
  feedCommentComposerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  commentsSheetBackground: {
    backgroundColor: '#161b22',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: '#30363d',
  },
  commentsSheetHandle: {
    backgroundColor: '#8b949e',
    width: 42,
  },
  commentsDrawerOverlay: {
    flex: 1,
  },
  commentsDrawerBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  commentsDrawerWrap: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  commentsDrawerSheet: {
    height: '72%',
    maxHeight: '92%',
    backgroundColor: '#161b22',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: '#30363d',
    overflow: 'hidden',
  },
  entryDrawerSheet: {
    height: '45%',
    maxHeight: '45%',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomWidth: 0,
  },
  commentsDrawerHandle: {
    alignSelf: 'center',
    width: 42,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#8b949e',
    marginTop: 10,
    marginBottom: 8,
  },
  commentsDrawerHandleWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 28,
  },
  commentsSheetHeader: {
    paddingHorizontal: 16,
    paddingTop: 0,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#30363d',
    backgroundColor: '#161b22',
    flexShrink: 0,
  },
  commentsSheetContent: {
    flex: 1,
    overflow: 'hidden',
  },
  commentsSheetList: {
    flex: 1,
  },
  commentsSheetSubtitle: {
    color: '#8b949e',
    fontSize: 12,
  },
  commentsSheetScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  commentsSheetItemGap: {
    height: 4,
  },
  commentsSheetComposerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 58,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 10,
    borderTopWidth: 1,
    borderTopColor: '#30363d',
    backgroundColor: '#161b22',
  },
  feedCommentInput: {
    flex: 1,
    marginBottom: 0,
    marginRight: 8,
    paddingVertical: 8,
  },
  chatGroupMessage: {
    color: '#c9d1d9',
    marginBottom: 4,
  },
  chatGroupMessageLast: {
    marginBottom: 2,
  },
  linkDanger: {
    color: '#ff7b72',
    marginTop: 6,
  },
  tabIslandDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 20,
    alignItems: 'center',
  },
  tabRow: {
    flexDirection: 'row',
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 999,
    backgroundColor: 'rgba(22, 27, 34, 0.95)',
    overflow: 'hidden',
    paddingHorizontal: 4,
    paddingVertical: 4,
    shadowColor: '#000000',
    shadowOpacity: 0.34,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  tabRowLight: {
    borderColor: '#d0d8e3',
    backgroundColor: 'rgba(247, 250, 255, 0.96)',
  },
  tabButton: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  tabButtonLight: {
    backgroundColor: 'transparent',
  },
  tabButtonActive: {
    backgroundColor: '#1f2a3a',
  },
  tabButtonActiveLight: {
    backgroundColor: '#e2ebfb',
  },
  tabButtonText: {
    color: '#f0f6fc',
    fontWeight: '600',
    fontSize: 12,
  },
  tabButtonTextLight: {
    color: '#1b1f24',
  },
  sectionTitle: {
    color: '#f0f6fc',
    fontSize: 18,
    fontWeight: '700',
    marginTop: 10,
    marginBottom: 8,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileHeaderText: {
    flex: 1,
    marginLeft: 12,
  },
  avatarSquare: {
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  chatInboxActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  chatFloatingHost: {
    position: 'relative',
    zIndex: 120,
  },
  chatScreenWrap: {
    position: 'relative',
  },
  dropdownBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 110,
  },
  floatingDropdown: {
    position: 'absolute',
    left: 0,
    right: 0,
    maxHeight: 360,
    backgroundColor: '#161b22',
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    zIndex: 130,
  },
  floatingDropdownInbox: {
    top: 116,
  },
  floatingDropdownRoom: {
    top: 160,
  },
  dropdownItem: {
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 8,
    padding: 8,
    marginBottom: 8,
  },
  chatListItem: {
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
    backgroundColor: '#161b22',
  },
  chatListItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chatBadge: {
    color: '#0d1117',
    backgroundColor: '#f2cc60',
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 2,
    fontSize: 12,
    fontWeight: '700',
  },
  chatRoomHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  socialWrap: {
    position: 'relative',
  },
  socialHeader: {
    marginBottom: 8,
  },
  segmentRow: {
    flexDirection: 'row',
    backgroundColor: '#161b22',
    borderRadius: 10,
    padding: 4,
    borderWidth: 1,
    borderColor: '#30363d',
    marginBottom: 8,
  },
  segmentButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 8,
  },
  segmentButtonActive: {
    backgroundColor: '#1f6feb',
  },
  segmentText: {
    color: '#f0f6fc',
    fontWeight: '600',
  },
  socialActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  socialDropdown: {
    top: 56,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    justifyContent: 'flex-start',
  },
  modalBackdropTapArea: {
    ...StyleSheet.absoluteFillObject,
  },
  modalCard: {
    marginHorizontal: 16,
    marginTop: 120,
    backgroundColor: '#161b22',
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    maxHeight: '70%',
  },
  socialModalCard: {
    marginTop: 180,
  },
  chatModalCard: {
    marginTop: 130,
  },
  entryActionsModalCard: {
    marginTop: 220,
  },
  homeDetailsModalCard: {
    marginTop: 90,
    height: '84%',
    paddingTop: 10,
  },
  homeDetailsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  homeDetailsTabRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  homeDetailsTabButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#30363d',
    backgroundColor: '#0f141b',
  },
  homeDetailsTabButtonActive: {
    borderColor: '#58a6ff',
    backgroundColor: 'rgba(31, 111, 235, 0.22)',
  },
  homeDetailsTabText: {
    color: '#8b949e',
    fontSize: 12,
    fontWeight: '600',
  },
  homeDetailsTabTextActive: {
    color: '#f0f6fc',
  },
  homeDetailsPager: {
    flex: 1,
  },
  homeDetailsPage: {
    flex: 1,
  },
  homeDetailsScroll: {
    flex: 1,
  },
  homeDetailsScrollContent: {
    paddingBottom: 24,
  },
  homeDetailsDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingTop: 8,
    paddingBottom: 2,
  },
  homeDetailsDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#30363d',
  },
  homeDetailsDotActive: {
    width: 16,
    borderRadius: 999,
    backgroundColor: '#58a6ff',
  },
  homeMapSection: {
    marginBottom: 10,
  },
  homeMapSectionFull: {
    flex: 1,
    marginBottom: 0,
  },
  homeMapTopActions: {
    position: 'absolute',
    top: '34%',
    right: 10,
    zIndex: 10,
    flexDirection: 'column',
    alignItems: 'center',
  },
  homeMapTopActionsLeft: {
    position: 'absolute',
    top: 56,
    left: 10,
    zIndex: 10,
    flexDirection: 'column',
    alignItems: 'center',
  },
  homeMapActionButton: {
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    marginTop: 8,
  },
  homeMapAddButton: {
    position: 'absolute',
    right: 16,
    bottom: 112,
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#238636',
    borderWidth: 1,
    borderColor: '#2ea043',
    zIndex: 12,
    shadowColor: '#000',
    shadowOpacity: 0.32,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  homeMapCard: {
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#121821',
  },
  homeMapCardFull: {
    flex: 1,
    borderWidth: 0,
    borderRadius: 0,
  },
  homeMap: {
    width: '100%',
    height: 380,
  },
  homeMapFull: {
    height: '100%',
  },
  homeMapFallback: {
    width: '100%',
    height: 220,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  homeMapEmptyHint: {
    color: '#8b949e',
    fontSize: 12,
    marginTop: 8,
  },
  homeMapLegendText: {
    color: '#8b949e',
    fontSize: 12,
    marginTop: 8,
  },
  homeMapHintOverlay: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 108,
    marginTop: 0,
    backgroundColor: 'rgba(15, 20, 27, 0.82)',
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  homeMapScreen: {
    flex: 1,
  },
  scrollBottomSpacer: {
    height: 120,
  },
  homeMapLoadingOverlay: {
    position: 'absolute',
    top: 64,
    alignSelf: 'center',
    zIndex: 20,
    backgroundColor: 'rgba(15,20,27,0.8)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#30363d',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  mapClusterMarker: {
    minWidth: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#1f6feb',
    borderWidth: 2,
    borderColor: '#f0f6fc',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  mapClusterMarkerText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  mapPinMarker: {
    minWidth: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#30363d',
    backgroundColor: '#0f141b',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  mapPinMarkerUpdating: {
    borderColor: '#58a6ff',
  },
  mapPinMarkerText: {
    fontSize: 16,
    lineHeight: 18,
  },
  mapPoopMarkerWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapPoopMarkerBubble: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(15, 20, 27, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0f141b',
    shadowOpacity: 0.28,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  mapPoopMarkerBubbleSelected: {
    borderColor: '#58a6ff',
    borderWidth: 2,
    shadowColor: '#58a6ff',
    shadowOpacity: 0.55,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 0 },
    elevation: 7,
  },
  mapPoopMarkerEmoji: {
    fontSize: 15,
    lineHeight: 17,
  },
  mapPoopMarkerTip: {
    marginTop: -3,
    width: 10,
    height: 10,
    transform: [{ rotate: '45deg' }],
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderColor: 'rgba(15, 20, 27, 0.35)',
  },
  mapPoopMarkerTipSelected: {
    borderColor: 'rgba(88, 166, 255, 0.95)',
    borderBottomWidth: 1.5,
    borderRightWidth: 1.5,
  },
  mapCurrentLocationWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 56,
    height: 56,
  },
  mapCrosshairOverlay: {
    position: 'absolute',
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 12,
  },
  mapCrosshairHorizontal: {
    position: 'absolute',
    width: 34,
    height: 2,
    borderRadius: 1,
    backgroundColor: 'rgba(88, 166, 255, 0.95)',
  },
  mapCrosshairVertical: {
    position: 'absolute',
    width: 2,
    height: 34,
    borderRadius: 1,
    backgroundColor: 'rgba(88, 166, 255, 0.95)',
  },
  mapCrosshairCenterDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#58a6ff',
    borderWidth: 1,
    borderColor: '#f0f6fc',
  },
  mapCurrentLocationDotOuter: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'rgba(240, 246, 252, 0.95)',
    backgroundColor: 'rgba(88, 166, 255, 0.24)',
    shadowColor: '#58a6ff',
    shadowOpacity: 0.55,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapCurrentLocationDotBody: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#2f81f7',
    borderWidth: 1,
    borderColor: '#7db6ff',
    shadowColor: '#0b2d5e',
    shadowOpacity: 0.45,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
    overflow: 'hidden',
  },
  mapCurrentLocationSpecular: {
    position: 'absolute',
    top: 2.5,
    left: 4,
    width: 5.5,
    height: 3,
    borderRadius: 3,
    backgroundColor: 'rgba(225, 240, 255, 0.45)',
  },
  mapCurrentLocationCenterDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#dcecff',
    backgroundColor: '#2f81f7',
    shadowColor: '#2f81f7',
    shadowOpacity: 0.35,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 3,
  },
  homeSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  monthStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  monthStatCard: {
    width: '49%',
    borderWidth: 1,
    borderColor: '#30363d',
    backgroundColor: '#161b22',
    borderRadius: 9,
    paddingVertical: 6,
    paddingHorizontal: 6,
    alignItems: 'center',
    marginBottom: 6,
  },
  monthStatValue: {
    color: '#f0f6fc',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 1,
  },
  monthStatLabel: {
    color: '#8b949e',
    fontSize: 9,
    textTransform: 'uppercase',
    letterSpacing: 0.25,
  },
  monthTipCard: {
    borderWidth: 1,
    borderColor: '#30363d',
    backgroundColor: '#161b22',
    borderRadius: 9,
    paddingVertical: 7,
    paddingHorizontal: 9,
    marginBottom: 8,
  },
  monthTipTitle: {
    color: '#f0f6fc',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 2,
  },
  monthTipText: {
    color: '#c9d1d9',
    fontSize: 11,
    lineHeight: 14,
  },
  selectedDayEntriesCard: {
    borderWidth: 1,
    borderColor: '#30363d',
    backgroundColor: '#161b22',
    borderRadius: 9,
    paddingVertical: 7,
    paddingHorizontal: 7,
    marginBottom: 8,
  },
  selectedDayEntriesTitle: {
    color: '#f0f6fc',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 5,
  },
  selectedDayEntriesRail: {
    paddingRight: 6,
  },
  selectedDayEntryItem: {
    width: 140,
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 9,
    backgroundColor: '#0f141b',
    padding: 6,
    marginRight: 6,
  },
  selectedDayEntryTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
    gap: 8,
  },
  selectedDayEntryTime: {
    color: '#8b949e',
    fontSize: 9,
    fontWeight: '600',
  },
  selectedDayEntryRating: {
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 2,
  },
  selectedDayEntryMeta: {
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 2,
  },
  selectedDayEntryNote: {
    color: '#c9d1d9',
    fontSize: 10,
    lineHeight: 13,
  },
  calendarCard: {
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 9,
    backgroundColor: '#121821',
    padding: 9,
    marginBottom: 10,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  calendarTitle: {
    color: '#f0f6fc',
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
  },
  calendarMonthButton: {
    width: 30,
    height: 30,
    marginRight: 0,
    marginBottom: 0,
  },
  calendarWeekRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  calendarWeekday: {
    width: '14.28%',
    textAlign: 'center',
    color: '#8b949e',
    fontSize: 10,
    fontWeight: '600',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  calendarCell: {
    width: '14.2857%',
    height: 34,
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#161b22',
    marginBottom: 3,
    position: 'relative',
    overflow: 'hidden',
  },
  calendarCellOutside: {
    borderColor: '#1f2937',
    backgroundColor: '#0f141b',
    opacity: 0.7,
  },
  calendarCellToday: {
    borderWidth: 2,
    borderColor: '#58a6ff',
    shadowColor: '#58a6ff',
    shadowOpacity: 0.35,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  calendarCellSelected: {
    borderWidth: 2,
    borderColor: '#f0f6fc',
  },
  calendarCellText: {
    color: '#f0f6fc',
    fontSize: 11,
    fontWeight: '600',
  },
  calendarEntryMarkerRow: {
    position: 'absolute',
    top: 2,
    right: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  calendarEntryDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#c9d1d9',
  },
  calendarEntryDotOutside: {
    opacity: 0.75,
  },
  calendarEntryPlus: {
    color: '#c9d1d9',
    fontSize: 7,
    fontWeight: '700',
    lineHeight: 8,
  },
  calendarCellTextToday: {
    color: '#ffffff',
    fontWeight: '800',
  },
  calendarCellTextOutside: {
    color: '#6e7681',
  },
  calendarLegendRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  calendarLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  calendarLegendSwatch: {
    width: 10,
    height: 10,
    borderRadius: 3,
    borderWidth: 1,
  },
  calendarLegendText: {
    color: '#8b949e',
    fontSize: 9,
  },
  entryRail: {
    paddingBottom: 6,
    paddingRight: 5,
  },
  entrySquareCard: {
    width: 132,
    height: 132,
    borderColor: '#30363d',
    borderWidth: 1,
    borderRadius: 10,
    padding: 7,
    marginRight: 7,
    backgroundColor: '#161b22',
    alignItems: 'center',
  },
  entrySquareCardSelected: {
    borderColor: '#58a6ff',
    borderWidth: 2,
    shadowColor: '#58a6ff',
    shadowOpacity: 0.28,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
  },
  entrySquareTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    position: 'relative',
    marginBottom: 3,
  },
  entrySquareMenuButton: {
    position: 'absolute',
    right: 0,
    top: 0,
  },
  entryTypeChip: {
    height: 24,
    minWidth: 64,
    borderRadius: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#30363d',
    backgroundColor: '#0f141b',
    justifyContent: 'center',
  },
  entryTypeDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 4,
  },
  entryTypeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#7b4d2a',
  },
  entryTypeDotHard: {
    backgroundColor: '#6d3f20',
  },
  entryTypeDotSoft: {
    backgroundColor: '#94623a',
  },
  entryTypePillLumpy: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#7f512d',
    position: 'relative',
  },
  entryTypeNotchA: {
    position: 'absolute',
    top: -1,
    left: 12,
    width: 6,
    height: 4,
    borderRadius: 3,
    backgroundColor: '#0f141b',
  },
  entryTypeNotchB: {
    position: 'absolute',
    bottom: -1,
    right: 16,
    width: 7,
    height: 4,
    borderRadius: 3,
    backgroundColor: '#0f141b',
  },
  entryTypePillCracked: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#8d5a32',
    position: 'relative',
    overflow: 'hidden',
  },
  entryTypeCrackA: {
    position: 'absolute',
    left: 14,
    top: 1,
    width: 1,
    height: 8,
    backgroundColor: '#5a341a',
    transform: [{ rotate: '14deg' }],
  },
  entryTypeCrackB: {
    position: 'absolute',
    right: 16,
    top: 1,
    width: 1,
    height: 8,
    backgroundColor: '#5a341a',
    transform: [{ rotate: '-12deg' }],
  },
  entryTypePillSmooth: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#9e6a3d',
    position: 'relative',
    overflow: 'hidden',
  },
  entryTypeHighlight: {
    position: 'absolute',
    left: 8,
    right: 8,
    top: 1,
    height: 2,
    borderRadius: 2,
    backgroundColor: '#c89262',
    opacity: 0.8,
  },
  entryTypeMushy: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#a87548',
    position: 'relative',
    overflow: 'hidden',
  },
  entryTypeMushyLayer: {
    position: 'absolute',
    left: 6,
    right: 6,
    top: 2,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#8f5f35',
    opacity: 0.8,
  },
  entryTypeMushyLayerSmall: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 1,
    height: 2,
    borderRadius: 2,
    backgroundColor: '#7d4f2b',
    opacity: 0.8,
  },
  entryTypeLiquid: {
    height: 10,
    borderRadius: 6,
    backgroundColor: '#b48356',
    position: 'relative',
    overflow: 'hidden',
  },
  entryTypeWaveA: {
    position: 'absolute',
    left: 6,
    right: 8,
    top: 3,
    height: 1,
    backgroundColor: '#8b5a33',
    opacity: 0.8,
  },
  entryTypeWaveB: {
    position: 'absolute',
    left: 10,
    right: 5,
    top: 6,
    height: 1,
    backgroundColor: '#7b4a25',
    opacity: 0.7,
  },
  entrySquareRating: {
    fontWeight: '700',
    fontSize: 11,
    marginBottom: 2,
    textAlign: 'center',
  },
  entrySquareMeta: {
    fontWeight: '700',
    fontSize: 10,
    marginBottom: 2,
    textAlign: 'center',
  },
  entrySquareTime: {
    color: '#8b949e',
    fontSize: 10,
    marginBottom: 3,
    textAlign: 'center',
  },
  volumeVisualCard: {
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    gap: 6,
  },
  volumeVisualEmoji: {
    fontSize: 28,
  },
  volumeVisualLabel: {
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  volumeOptionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  volumeOptionButton: {
    width: '18%',
    minWidth: 62,
    flexGrow: 1,
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  volumeOptionEmoji: {
    fontSize: 18,
  },
  volumeOptionText: {
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  entrySquareNote: {
    color: '#c9d1d9',
    fontSize: 10,
    lineHeight: 12,
    flex: 1,
    textAlign: 'center',
    width: '100%',
  },
  entryInlineMenu: {
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: '#0d131c',
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 12,
    padding: 8,
    zIndex: 50,
    shadowColor: '#000000',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 14,
  },
  entryInlineMenuIconOnly: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#243040',
    backgroundColor: '#121a24',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  entryInlineMenuTitle: {
    color: '#8b949e',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginLeft: 4,
  },
  entryInlineMenuItem: {
    minHeight: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#243040',
    backgroundColor: '#121a24',
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  entryInlineMenuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  entryInlineMenuItemIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  entryInlineMenuItemIconEdit: {
    backgroundColor: 'rgba(56, 139, 253, 0.22)',
  },
  entryInlineMenuItemIconDelete: {
    backgroundColor: 'rgba(248, 81, 73, 0.2)',
  },
  entryInlineMenuItemText: {
    color: '#f0f6fc',
    fontSize: 13,
    fontWeight: '600',
  },
  entryInlineMenuItemTextDanger: {
    color: '#ff7b72',
  },
  entryMenuBackdrop: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  entryActionDrawerContent: {
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  entryActionDrawerTitle: {
    color: '#8b949e',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.35,
    marginBottom: 10,
  },
  entryActionDrawerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  entryActionDrawerButton: {
    flex: 1,
    minHeight: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#2b394d',
    backgroundColor: '#121a24',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  entryActionDrawerButtonDanger: {
    borderColor: '#7e3b3f',
    backgroundColor: '#261518',
  },
  entryActionDrawerButtonText: {
    color: '#c9d1d9',
    fontSize: 12,
    fontWeight: '700',
  },
  entryActionDrawerButtonTextDanger: {
    color: '#ff7b72',
  },
  bristolGuide: {
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 10,
    padding: 8,
    marginBottom: 10,
    backgroundColor: '#0f141b',
  },
  bristolGuideRow: {
    color: '#c9d1d9',
    marginBottom: 3,
    fontSize: 12,
  },
  bristolQuickSelectRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 10,
    marginBottom: 2,
  },
  bristolQuickSelectWrap: {
    marginTop: 10,
    marginBottom: 2,
    gap: 8,
  },
  bristolQuickSelectRowTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  bristolQuickSelectRowBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: '12.5%',
  },
  bristolQuickSelectButton: {
    width: '13%',
    minWidth: 34,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    marginBottom: 6,
  },
  bristolQuickSelectButtonStagger: {
    marginTop: 6,
  },
  bristolQuickSelectText: {
    fontSize: 12,
    fontWeight: '700',
  },
  bristolQuickSelectButtonVisual: {
    flex: 1,
    minHeight: 44,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  sliderEndLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
    marginBottom: 8,
  },
  sliderEndLabel: {
    color: '#8b949e',
    fontSize: 11,
  },
  dateTimePickerWrap: {
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 10,
    padding: 8,
    backgroundColor: '#121821',
  },
  timeEditorWrap: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    gap: 8,
  },
  timeEditorRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  timeEditorButton: {
    flex: 1,
    minHeight: 34,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeEditorValuesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  timeEditorValue: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '700',
    minWidth: 56,
    textAlign: 'center',
  },
  timeEditorColon: {
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '600',
  },
  timeEditorPeriodWrap: {
    marginLeft: 10,
    gap: 6,
  },
  timeEditorPeriodButton: {
    minWidth: 54,
    minHeight: 30,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeEditorPeriodText: {
    fontSize: 12,
    fontWeight: '700',
  },
  dateTimeSpacer: {
    width: 8,
  },
  ratingVisualCard: {
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 10,
    padding: 8,
    marginBottom: 8,
    backgroundColor: '#121821',
  },
  ratingVisualTitle: {
    color: '#c9d1d9',
    fontSize: 12,
    marginBottom: 6,
  },
  ratingPillRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 4,
  },
  ratingPill: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 4,
    backgroundColor: '#0f141b',
    alignItems: 'center',
  },
  ratingPillActive: {
    borderWidth: 2,
    transform: [{ translateY: -1 }],
  },
  ratingPillEmoji: {
    color: '#f0f6fc',
    fontSize: 14,
    fontWeight: '700',
  },
  ratingPillLabel: {
    color: '#8b949e',
    fontSize: 10,
    marginTop: 2,
    textAlign: 'center',
  },
  bristolVisualCard: {
    borderWidth: 1,
    borderColor: '#30363d',
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    backgroundColor: '#121821',
    alignItems: 'center',
    overflow: 'hidden',
  },
  bristolVisualGlyphWrap: {
    height: 26,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bristolVisualText: {
    color: '#c9d1d9',
    fontSize: 12,
    marginTop: 8,
  },
  bristolDotsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  bristolDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    overflow: 'hidden',
  },
  bristolBlob: {
    width: 14,
    height: 11,
    borderRadius: 7,
  },
  bristolDotHard: {
    backgroundColor: '#8a6a4f',
  },
  bristolDotSoft: {
    backgroundColor: '#a88360',
  },
  bristolDotSkewA: {
    transform: [{ rotate: '-11deg' }],
  },
  bristolDotSkewB: {
    transform: [{ rotate: '8deg' }],
  },
  bristolBlobA: {
    transform: [{ rotate: '-14deg' }],
  },
  bristolBlobB: {
    transform: [{ rotate: '10deg' }],
  },
  bristolLumpySausage: {
    width: 110,
    height: 18,
    borderRadius: 10,
    backgroundColor: '#8a6a4f',
    borderWidth: 2,
    borderColor: '#6a4f3a',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  bristolContourLine: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: 'rgba(70,50,37,0.5)',
  },
  bristolTextureRow: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  bristolTextureDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#5b4532',
  },
  bristolSmoothSausage: {
    width: 120,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#9a7755',
    overflow: 'hidden',
  },
  bristolCracked: {
    borderTopWidth: 2,
    borderTopColor: '#6a4f3a',
  },
  bristolCrackMarkA: {
    position: 'absolute',
    top: 4,
    left: 28,
    width: 10,
    height: 2,
    backgroundColor: '#6a4f3a',
    transform: [{ rotate: '-23deg' }],
  },
  bristolCrackMarkB: {
    position: 'absolute',
    top: 5,
    left: 55,
    width: 9,
    height: 2,
    backgroundColor: '#6a4f3a',
    transform: [{ rotate: '18deg' }],
  },
  bristolCrackMarkC: {
    position: 'absolute',
    top: 5,
    left: 83,
    width: 9,
    height: 2,
    backgroundColor: '#6a4f3a',
    transform: [{ rotate: '-16deg' }],
  },
  bristolHighlight: {
    position: 'absolute',
    top: 2,
    left: 12,
    right: 24,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(240,246,252,0.25)',
  },
  bristolHighlightSoft: {
    position: 'absolute',
    top: 7,
    left: 24,
    right: 32,
    height: 2,
    borderRadius: 2,
    backgroundColor: 'rgba(240,246,252,0.16)',
  },
  bristolShadowBand: {
    position: 'absolute',
    left: 8,
    right: 8,
    bottom: 2,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(60,42,30,0.35)',
  },
  bristolMushy: {
    width: 120,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#b08a66',
    opacity: 0.85,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  bristolMushyLayer: {
    position: 'absolute',
    left: 10,
    right: 10,
    height: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(140,102,72,0.45)',
  },
  bristolMushyLayerSmall: {
    position: 'absolute',
    left: 35,
    right: 35,
    height: 7,
    borderRadius: 6,
    backgroundColor: 'rgba(90,63,44,0.35)',
  },
  bristolMushyGrainA: {
    position: 'absolute',
    left: 20,
    top: 6,
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(95,70,49,0.4)',
  },
  bristolMushyGrainB: {
    position: 'absolute',
    right: 24,
    bottom: 5,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(95,70,49,0.35)',
  },
  bristolLiquid: {
    width: 120,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#c8a27e',
    opacity: 0.7,
    overflow: 'hidden',
  },
  bristolWaveA: {
    position: 'absolute',
    left: -6,
    right: -6,
    top: 3,
    height: 4,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  bristolWaveB: {
    position: 'absolute',
    left: -12,
    right: -12,
    bottom: 2,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(110,84,64,0.35)',
  },
  bristolWaveC: {
    position: 'absolute',
    left: 8,
    right: 24,
    top: 1,
    height: 2,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  bristolDotSpecular: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(240,246,252,0.18)',
  },
  bristolDotSpecularSoft: {
    position: 'absolute',
    top: 2,
    left: 3,
    width: 4,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(240,246,252,0.15)',
  },
});
